### PR TITLE
fixed the alignment issue of team members

### PR DESCRIPTION
**Pull request by hexwhiz**
## Description

The alignment of the names of winners was not right. It was because the divs with `.podium-items` class were flex items because they are inside the `.container` div which is a flex container and had `align-items:flex-end;`. That's why the names were aligned to the end of the container. I fixed the issue by converting each `.podium-items` div into css grid of 2 rows and 1 column. Then changing the `align-items:` to `stretch` and setting relevant height did the job.

## Related Issue

Fixes # 1

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Motivation and Context

The change is required because it makes the leaderboard look cleaner and easier to read. 

## How Has This Been Tested?

I tried to increase the length of the name of a winner, and it was still aligning perfectly. Even in the mobile viewport the alignment is ok.
### Steps to reproduce:
- Open inspect tools and find the html part where the names of winners are written using select tool.
- Try to increase the length of any of the name.
- Try changing the viewport size.

## Screenshots (if appropriate):
Untitled

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

**Test Configuration**:
* Firmware version: 
* Hardware: 
* Toolchain: 
* SDK:

### CODE REVIEW

**Comment by meisabhishekpatel** [comment]
@hexwhiz i don't want the podium like this the leader (middle person) should be at the top

**Comment by hexwhiz** [comment]
Ok @meisabhishekpatel  I will fix that. I have got 2 hrs remaining so if the timer runs out, can I still make the PR?

**Comment by hexwhiz** [comment]
@meisabhishekpatel Is this ok?
image

**Comment by hexwhiz** [comment]
I have added a new commit regarding the height issue. I also added some margin to team names so that name of middle person doesn't overlap with the team's name when zoomed.

**Comment by hexwhiz** [comment]
@meisabhishekpatel would you please review my PR?

**Review by meisabhishekpatel — APPROVED** [review]

**Comment by meisabhishekpatel** [comment]
closes #1

**Pull request merged**
